### ISSUE TITLE
[manager] rata tengahkan secara vertikal text daftar kategori

### ISSUE THREAD

**Issue by elberthomax** [stevelukis/vanilla-js-restaurant#21]
![image](https://user-images.githubusercontent.com/38391861/49376106-232eba80-f741-11e8-9cdb-75765145236b.png)

**Comment by andiwijayaid** [comment]
nda bisa CORS ku lagi... besok coba di laptop mu @elberthomax

**Comment by andiwijayaid** [comment]
Done, push from @elberthomax
